    
insert into spellingBee
    (word, word2, partOfSpeech, definition, difficulty)
values 
    (1,"PUNTING",'',"verb","to kick a ball when playing football, soccer or rugby before the ball hits the ground when dropped from the hands.","easy"),
(2,"CROWD",'',"noun","a large number of people especially when condensed into a compact group without order.","easy"),
(3,"SECRET",'',"adjetive","hidden, concealed.","easy"),
(4,"FUMBLE",'',"verb","to move awkwardly along, feeling one's way.","easy"),
(5,"POND",'',"noun","a body of water that is smaller than a lake but larger than a pool, and that either occurs naturally or is confined through man-made means.","easy"),
(6,"PARDON",'',"noun","forgiveness of a fault or offense.","easy"),
(7,"SHAKE",'',"verb","to grip or join hands.","easy"),
(8,"KIDDO",'',"noun","used as a familiar way to greet someone.","easy"),
(9,"PROOF",'',"noun","anything serving as evidence to determine the judgment or finding of a court of law.","easy"),
(10,"GORP",'',"noun","a snack that is usually comprised of high-energy foods such as nuts.","easy"),
(11,"TOWN",'',"noun","a compressed settled area that in terms of population is larger than a village but smaller than a city.","easy"),
(12,"BINGO",'',"noun","a game played using a grid in which five covered numbers in a row means a win.","easy"),
(13,"CLEVER",'',"adjetive","having quick mental faculties, intelligence and resourcefulness in improvising accompanied by cunning wit or physical readiness and grace.","easy"),
(14,"INSIDE",'',"adjetive","being on an inner surface or side.","easy"),
(15,"REPLY",'',"verb","to answer in words or writing.","easy"),
(16,"FROZEN",'',"adjetive","subject to severe cold : chilly.","easy"),
(17,"SPECIAL",'',"adjetive","noteworthy, extraordinary, uncommon.","easy"),
(18,"FILM",'',"verb","to make a movie of.","easy"),
(19,"RESULTS",'',"plurl noun","a comprehensive publication of the outcome of competitive events.","easy"),
(20,"SODA",'',"noun","a beverage that consists of water which is highly charged with carbon dioxide that is used to make soft drinks.","easy"),
(21,"SEAL",'',"noun","a marine aquatic carnivorous mammal that lives near cold seacoasts or on floating ice, bears its young on land, feeds on fish and other marine animals, has webbed flippers adapted for swimming, and has been hunted for its fur, hide and oil.","easy"),
(22,"TWIRLED",'',"verb","spun quickly.","easy"),
(23,"CRATE",'',"noun","a container that is used to transport items.","easy"),
(24,"ADMIT",'',"verb","to accept as the truth.","easy"),
(25,"GROWN-UPS",'',"plurl noun","adults : those that have reached full physical and intellectual development.","easy"),
(26,"PIECES",'',"plurl noun","parts of a whole thing.","easy"),
(27,"BRASS",'',"noun","a typically yellow alloy made of copper with zinc which is capable of being formed and is harder and stronger than copper.","easy"),
(28,"ONSHORE",'',"adveb","within the country.","easy"),
(29,"STUNTS",'',"plurl noun","feats or tricks which display significant strength or skill.","easy"),
(30,"DENY",'',"verb","to turn down or give a negative answer to a person.","easy"),
(31,"JOLLY",'',"adjetive","joyous.","easy"),
(32,"POWDER",'',"noun","a substance made up of very fine particles.","easy"),
(33,"HOTEL",'',"noun","a building with many rooms that are used for overnight lodging.","easy"),
(34,"WALNUT",'',"noun","an edible nut that comes from a tree of the same name.","easy"),
(35,"SAWDUST",'',"noun","dry pulverized particles of wood or stone made during the process of cutting material with a manually operated or power-driven tool.","easy"),
(36,"FLUSTERED",'',"verb","confused, muddled.","easy"),
(37,"BARBER",'',"noun","one whose job is to cut and dress hair, as well as shave and trim beards.","easy"),
(38,"CHIMES",'',"verb","makes a musical and harmonious sound, like a bell.","easy"),
(39,"CABIN",'',"noun","a small single-story low-roofed house of simple construction.","easy"),
(40,"FAINT",'',"adjetive","feeble, dizzy and likely to pass out due to hunger, illness, pain, shock or emotion.","easy"),
(41,"MANGER",'',"noun","an open box in which food is placed for horses or cattle to eat.","easy"),
(42,"PEPPERMINT",'',"noun","a sharp and strong smelling plant with dark green leaves and whorls of small pink flowers in spikes.","easy"),
(43,"BROTH",'',"noun","liquid which was used to cook meat, fish, grains or vegetables.","easy"),
(44,"ASH",'',"noun","the material that is left behind after combustible materials such as coal have been burned.","easy"),
(45,"FLAME",'',"noun","the part of a fire which glows.","easy"),
(46,"GRITS",'',"plurl noun","grains such as maize, wheat or barley which have been hulled and coarsely ground.","easy"),
(47,"CLIFF",'',"noun","a very steep face of rock or earth : precipice.","easy"),
(48,"HEM",'',"noun","an edge of cloth such as for a skirt, sleeve or napkin which has been finished by folding back the edge and sewing it down.","easy"),
(49,"CANDLES",'',"plurl noun","long, slender, cylindrical masses made of wax and containing wicks that are burned to give light.","easy"),
(50,"BRIM",'',"noun","the edge of a cup or bowl.","easy"),
(51,"PLOT",'',"verb","to devise or plan.","easy"),
(52,"DESK",'',"noun","a table with a sloping or horizontal surface used for writing and reading, often furnished with drawers and compartments.","easy"),
(53,"BOBCAT",'',"noun","a lynx from North America that is reddish with dark markings.","easy"),
(54,"POLO",'',"noun","a game played by teams of three or four players on horseback who use mallets with long handles to move a wooden ball down the field and through goalposts.","easy"),
(55,"ROLLER",'',"noun","a device made of a rotating cylinder that is covered with an absorbent material and mounted on a handle so that the cylinder can be dipped into paint and rolled over a flat surface such as a wall.","easy"),
(56,"STARK",'',"adjetive","barren, desolate, bleak.","easy"),
(57,"DRUM",'',"noun","a musical percussion instrument that usually consists of a hollow cylinder with a skin head stretched over it which is beaten with a stick or pair of sticks.","easy"),
(58,"SNARL",'',"noun","a tangle of something such as hairs or threads that is difficult to unravel.","easy"),
(59,"ARGUE",'',"verb","to give statements or provide facts in support of or in opposition to an opinion.","easy"),
(60,"LOPPERS",'',"plurl noun","shears used for pruning which are about two feet in length.","easy"),
(61,"PETAL",'',"noun","one of the typically leaf-shaped members that make up the inner set of leaves of a flower.","easy"), 
(62,"GIANT",'',"adjetive","extremely large.","easy"),
(63,"SNIFFLE",'',"verb","to bring air noisily up into the nose over and over again to stop mucus from running from the nose typical of having a cold.","easy"),
(64,"MOUTH",'',"noun","the opening for food to enter the body of an animal.","easy"),
(65,"FILTERS",'',"plurl noun","porous articles typically made from cloth, paper or sand used to separate liquid or gas from solid matter by passing the matter through the article.","easy"),
(66,"CONE",'',"noun","a crisp conical wafer used to hold ice cream.","easy"),
(67,"NEVER",'',"adveb","at no time.","easy"),
(68,"SILLY",'',"adjetive","of little weight or importance.","easy"),
(69,"MONDAY",'',"noun","the second day of the week.","easy"),
(70,"GRUB",'',"noun","food.","easy"),
(71,"HOOK",'',"noun","a curved piece of metal or other hard material that is used for catching, holding or pulling.","easy"),
(72,"NUMBER",'',"noun","the total sum of units involved.","easy"),
(73,"COOKING",'',"verb","preparing food for the table by a heating process.","easy"),
(74,"AMAZED",'',"adjetive","filled with wonder : astounded.","easy"),
(75,"COLLECT",'',"verb","to gather together into a group or assortment.","easy"),
(76,"LOCAL",'',"adjetive","characterized by or confined to a particular place : not widespread.","easy"),
(77,"PROPER",'',"adjetive","marked by being suitable, fit, compatible or in accordance.","easy"),
(78,"BASEMENT",'',"noun","the part of a building that is either completely or partly below the ground level.","easy"),
(79,"RIPPLE",'',"verb","to become lightly ruffled on the surface such as can occur with water.","easy"),
(80,"FEATS",'',"plurl noun","deeds or acts.","easy"),
(81,"PLUMBING",'',"noun","the articles such as pipes and fixtures in a building that are concerned with the introduction, distribution and disposal of water.","easy"),
(82,"STUBBORN",'',"adjetive","perversely unyielding in character or quality.","easy"),
(83,"ADRIFT",'',"adveb","without anchor or mooring and without controlled direction.","easy"),
(84,"SWEETEN",'',"verb","to add sugar to.","easy"),
(85,"NEON",'',"adjetive","extremely bright in color.","easy"),
(86,"BEESWAX",'',"noun","business — used primarily by children.","easy"),
(87,"SOCIAL",'',"adjetive","marked by pleasant time spent with one's friends or companions.","easy"),
(88,"BEHOLD",'',"verb","to experience or apprehend : to receive the full impression of something through sight.","easy"),
(89,"MIX",'',"verb","to stir, shake or bring different substances together.","easy"),
(90,"DROOL",'',"noun","saliva issuing from the mouth in a stream.","easy"),
(91,"UNDERSTAND",'',"verb","to comprehend.","easy"),
(92,"STRAY",'',"noun","a domestic animal that has left its enclosure or home and wanders at large or is lost.","easy"),
(93,"SOUND",'',"noun","a noise or tone.","easy"),
(94,"BENCHES",'',"plurl noun","long typically wooden seats for multiple people to sit upon.","easy"),
(95,"SHRUGGED",'',"verb","raised the shoulders to express indifference or aloofness.","easy"),
(96,"STILL",'',"adjetive","stationary, immobile.","easy"),
(97,"PRANKS",'',"plurl noun","tricks.","easy"),
(98,"SMILED",'',"verb","looked at with amusement, contempt or ridicule.","easy"),
(99,"PEACH",'',"noun","a sweet juicy edible fruit which is used as a fresh or cooked fruit, in preserves or dried.","easy"),
(100,"PIE",'',"noun","a food consisting of meat or fruit baked in or under dough and typically in a dish that is lined with dough and topped with pastry.","easy"),
(101,"SIZE",'',"noun","the actual, characteristic, normal or relative proportion of a thing.","easy"),
(102,"HALL",'',"noun","the home or castle of a medieval king or member of the nobility.","easy"),
(103,"JANGLED",'',"verb","caused to sound harshly or unpleasantly.","easy"),
(104,"CHAIN",'',"noun","a series of interconnected typically metal links or rings used for various purposes such as support or restraint.","easy"),
(105,"WORKHORSE",'',"noun","a person who performs and takes on a large amount of difficult labor.","easy"),
(106,"ANTENNAS",'',"plurl noun","metallic devices such as rods or wires that are used for receiving or radiating radio waves.","easy"),
(107,"HONEST",'',"adjetive","legitimate : truthful.","easy"),
(108,"HOLLER",'',"verb","to cry out or shout to attract attention.","easy"),
(109,"BILLBOARD",'',"noun","a large panel mounted on a building or framework near a road that holds outdoor advertising.","easy"),
(110,"CHICKEN",'',"noun","a common domestic bird.","easy"),
(111,"PUPPETS",'',"plurl noun","representations of humans or other living things that are small in scale and are moved and controlled by rod, hand or strings.","easy"),
(112,"WAITED",'',"verb","remained in place in expectation of something or someone.","easy"),
(113,"FINISH",'',"verb","to arrive at the end of : complete.","easy"),
(114,"CHEER",'',"verb","to fill with gladness : to cause to be happy.","easy"),
(115,"TWISTY",'',"adjetive","winding : full of bends.","easy"), 
(116,"CHIPS",'',"plurl noun","thin slices of potatoes that are deep-fried in fat.","easy"),
(117,"SCOOP",'',"noun","a container or utensil used to hold or remove a liquid or loose materials.","easy"),
(118,"ROVER",'',"noun","someone who wanders.","easy"),
(119,"FORGIVE",'',"verb","to stop feeling resentment toward because of a wrong committed.","easy"),
(120,"RIBBON",'',"noun","a flat narrow fabric made of silk, rayon, nylon or cotton that is closely woven in various constructions and used for trimmings, decorations or knitting.","easy"),
(121,"SHOO",'',"intejection","— used in scaring away an animal.","easy"),
(122,"GREEDY",'',"adjetive","having an excessive or selfish desire for something, usually material possessions.","easy"),
(123,"BEAM",'',"noun","a long piece of heavy wood that is suitable to use in house construction.","easy"),
(124,"CREW",'',"noun","the group of people who work on a ship.","easy"),
(125,"DISEMBARK",'',"verb","to leave or go ashore from a ship.","medium"),
(126,"EARTHQUAKE",'',"noun","a trembling or shaking of the earth that accompanies crustal movements.","medium"),
(127,"BROUGHT",'',"verb","conveyed or carried along from one place to another.","medium"),
(128,"GALLOP",'',"noun","the natural three-beat gait of a horse.","medium"),
(129,"DINOSAUR",'',"noun","a member of a group of extinct reptiles.","medium"),
(130,"ANCIENT",'',"adjetive","existing from a long ago period or date.","medium"),
(131,"TAPESTRY",'',"noun","a heavy textile woven by hand used for hangings or curtains.","medium"),
(132,"DELIVERY",'',"noun","an instance of the physical transfer of a shipment.","medium"),
(133,"ATTAGIRL",'',"intejection","— used to express encouragement or approval to a woman or girl.","medium"),
(134,"SALAMANDERS",'',"plurl noun","various small amphibians that resemble lizards but don't have scales, are covered with a soft moist skin, live in moist dark places, pose no harm to humans, and feed on small animals such as aquatic worms and insects.","medium"),
(135,"USUAL",'',"adjetive","in accordance with the normal custom, usage or habit.","medium"),
(136,"CHALLENGE",'',"noun","a thing which one can devote energy or effort to.","medium"),
(137,"CAHOOTS",'',"plurl noun","secret agreement : collusion.","medium"),
(138,"OOZING",'',"verb","moving slowly or without notice.","medium"),
(139,"MARS",'',"noun","the planet that is fourth from the sun and is noted for its apparent red color.","medium"),
(140,"PELICAN",'',"noun","a large web-footed bird with long wings and a very large bill having a throat pouch in which it catches fish.","medium"),
(141,"DRASTIC",'',"adjetive","notably vigorous or severe.","medium"),
(142,"YOGA",'',"noun","a group of exercises for achieving well-being and control of mind and body.","medium"),
(143,"BURLAP",'',"noun","a course heavy plain-woven fabric typically made from hemp or jute that is used for bagging and wrapping items.","medium"),
(144,"BLAZER",'',"noun","a single-breasted sports jacket usually with bright stripes or in a solid color that has a notched collar and patch pockets.","medium"),
(145,"TROMBONE",'',"noun","a brass instrument that consists of a long cylindrical metal tube that ends in a bell and has a movable slide which makes musical sounds.","medium"),
(146,"TREMBLING",'',"verb","quaking due to fear or another emotion.","medium"),
(147,"CALMED",'',"verb","made peaceful : induced quiet and peace in place of agitation or passion.","medium"),
(148,"POLICE",'',"noun","the department of the government which is concerned with maintaining public order, safety and health, and which has the power to enforce laws.","medium"),
(149,"CERTAIN",'',"adjetive","given to or marked by complete conviction and assurance.","medium"),
(150,"BAROGRAPH",'',"noun","an automatic instrument which is used to record variations in atmospheric pressure.","medium"),
(151,"CHARRED",'',"verb","partly burned on the outside.","medium"),
(152,"PAKISTAN",'',"geogaphical entry","a country in southern Asia which borders the Arabian Sea.","medium"),
(153,"PRESSURE",'',"noun","the burden of mental or physical distress.","medium"),
(154,"SURMISED",'',"verb","guessed : formed an opinion without substantial proof or certain knowledge.","medium"),
(155,"TEAK",'',"noun","the hard, strong, durable, yellowish brown wood of a tall East Indian timber tree which is highly resistant to insect attack and warping and is used for shipbuilding.","medium"),
(156,"TRANSIT",'',"noun","the public transportation of people by bus, subway train or other local system of conveyance.","medium"),
(157,"CANNONADE",'',"noun","a noisy persistent attack as of questions.","medium"),
(158,"APPETITE",'',"noun","the desire to eat when food is available.","medium"),
(159,"LUGGAGE",'',"noun","suitcases, bags used for travel or other articles used to carry a traveler's belongings.","medium"),
(160,"RAMPARTS",'',"plurl noun","protective barriers.","medium"),
(161,"VINYL",'',"noun","any of a group of tough durable plastics based on resins that are used especially in the forming of films and sheeting, flooring, and sound records.","medium"),
(162,"ANEMOMETERS",'',"plurl noun","tools used to gauge the speed of the wind.","medium"),
(163,"DAINTY",'',"adjetive","characterized by beauty that is delicate in nature.","medium"),
(164,"BUCKLE",'',"verb","to secure two loose ends of something such as a belt with one end having a fastening and the other a catch.","medium"),
(165,"VIVIDLY",'',"adveb","intensely, sharply, keenly.","medium"),
(166,"BRINY",'',"adjetive","salty.","medium"),
(167,"PAVEMENT",'',"noun","the surface of a public thoroughfare which is artificially covered.","medium"),
(168,"GARNET",'',"noun","a brittle material which is typically red in color and occurs mainly in crystals.","medium"),
(169,"FURROW",'',"verb","to cultivate or till as if with a plow.","medium"),
(170,"SPRAWL",'',"verb","to lie or sit with arms and legs stretched out : to spread out.","medium"),
(171,"MUSEUM",'',"noun","a building or institution which is devoted to the gathering, care, study and display of objects of lasting interest and value.","medium"),
(172,"WREN",'',"noun","any of various small brown singing birds.","medium"),
(173,"LEGEND",'',"noun","someone having a special status as a result of possessing extraordinary qualities that are typically partly real and partly mythical.","medium"),
(174,"TRANSISTOR",'',"noun","an electronic device made of a small block of a semiconductor with three electrodes on it and that conducts electrons moving in one direction to the opposite direction.","medium"),
(175,"AMPLIFY",'',"verb","to expand, extend or enlarge a statement or idea by adding details or illustration.","medium"),
(176,"SECURITY",'',"noun","freedom from care, anxiety or fear.","medium"),
(177,"REFRAIN",'',"noun","a phrase or verse that recurs regularly typically within a poem or song.","medium"),
(178,"TACTICS",'',"plurl noun","methods : systems of procedure.","medium"),
(179,"SHEPHERD",'',"noun","a man employed in tending, feeding and guarding sheep.","medium"),
(180,"ANGUS",'',"noun","any of a breed of hornless black or red beef cattle originally from Scotland.","medium"),
(181,"MULISH",'',"adjetive","stubborn, inflexible or uncompromising.","medium"),
(182,"RIVALRY",'',"noun","competition.","medium"),
(183,"SIBLINGS",'',"plurl noun","two or more people with the same parents.","medium"),
(184,"CHESTNUT",'',"noun","any of a genus of deciduous trees or shrubs native to temperate regions of the northern hemisphere that have a fruit consisting of a single nut.","medium"),
(185,"MINIVAN",'',"noun","a small multipurpose vehicle with rear or side doors and side panels with windows that is used to transport passengers.","medium"),
(186,"PLAID",'',"adjetive","having a cross-barred multicolored pattern.","medium"),
(187,"TISSUE",'',"noun","an aggregate of cells together with their intercellular substance that form one of the structural materials out of which the body of a plant or an animal is made.","medium"),
(188,"SCOUNDREL",'',"noun","a bold selfish person who is equipped with low ethical standards.","medium"),
(189,"AMINO",'',"adjetive","relating to or containing the group NH2 united to a radical other than an acid radical.","medium"),
(190,"MENTHOL",'',"noun","an alcohol that occurs naturally in peppermint oil and Japanese mint oil and can be made artificially.","medium"),
(191,"TABASCO",'',"tradmark","— used for a condiment sauce made from capsicum berries.","medium"),
(192,"OBVIOUS",'',"adjetive","easily perceived by the mind.","medium"),
(193,"PULSE",'',"noun","a regular wave of distension in the arteries that is a result of blood progressing through an artery at each contraction of the ventricles of the heart.","medium"),
(194,"COTTAGE",'',"noun","a small house typically used in the summer.","medium"),
(195,"GARLAND",'',"noun","a wreath of leaves or flowers that is worn on the head or used for decoration.","medium"),
(196,"GNAW",'',"verb","to bite or chew on with the teeth.","medium"),
(197,"COMFORT",'',"noun","enjoyment in physical or mental well-being.","medium"),
(198,"CAROLING","CAROLLING","verb","traveling outside in a group to sing Christmas songs on Christmas Eve.","medium"),
(199,"FOOLISHNESS",'',"noun","the state of lacking seriousness : folly.","medium"),
(200,"CONSTELLATION",'',"noun","any of the 88 configurations of stars.","medium"),
(201,"SUNDERING",'',"verb","breaking or forcing apart.","medium"),
(202,"JUNCTURE",'',"noun","a seam or joint.","medium"),
(203,"EXPLOITS",'',"verb","takes undue advantage of.","medium"),
(204,"RABBLE-ROUSER",'',"noun","a person who stirs up the masses of the people such as to violence or hatred.","medium"),
(205,"PROFOUND",'',"adjetive","hard to understand or comprehend.","medium"),
(206,"WREATH",'',"noun","a crown or band of intertwined flowers or leaves worn or given as a mark of honor.","medium"),
(207,"PROFILE",'',"noun","a representation of something in outline.","medium"),
(208,"UNTOWARD",'',"adjetive","unfortunate or unlucky.","medium"),
(209,"MEMORIAL",'',"adjetive","commemorative.","medium"),
(210,"INDUSTRIAL",'',"adjetive","of or belonging to a department of a craft, business or manufacture.","medium"),
(211,"BARRIER",'',"noun","an object or objects that serve to separate or keep items apart.","medium"),
(212,"GRATINGLY",'',"adveb","with an irritating or harsh effect or sound.","medium"),
(213,"BRAYED",'',"verb","made a loud harsh cry — used of a donkey.","medium"),
(214,"HARLEM",'',"geogaphical entry","section of New York City in northern Manhattan that was a center of African American culture in the 1920s.","medium"),
(215,"MESSENGER",'',"noun","someone who delivers a written or oral communication : a courier.","medium"),
(216,"BEACONS",'',"plurl noun","fires placed on a hill or tower that are used to communicate signals.","medium"),
(217,"GENERATION",'',"noun","development, rise.","medium"),
(218,"COVERAGE",'',"noun","the amount of reporting given to a news event.","medium"),
(219,"DETERS",'',"verb","turns aside or discourages from acting.","medium"),
(220,"NEPAL",'',"geogaphical entry","landlocked country in Asia in the Himalayas on the northeast border of India.","medium"),
(221,"DISINFECTANT",'',"noun","a chemical used to destroy vegetative forms of damaging microorganisms.","medium"),
(222,"CAMPAIGN",'',"noun","a period of continuous and often competitive activity in any seasonal occupation or industry.","medium"),
(223,"STARVATION",'',"noun","the instance of suffering from extreme hunger.","medium"),
(224,"GAMMA",'',"noun","the third letter of the Greek alphabet.","medium"),
(225,"SPLEEN",'',"noun","an abdominal organ that plays a role in the maintenance of blood volume, the production of blood cells, the recovery of material from worn-out blood cells and the production of antibodies.","medium"),
(226,"UTENSILS",'',"plurl noun","tools or instruments used in a kitchen.","medium"),
(227,"DEPOT",'',"noun","a bus station.","medium"),
(228,"INCIDENT",'',"noun","an uncommon happening.","medium"),
(229,"BRAMBLES",'',"plurl noun","prickly and rough vines or shrubs.","medium"),
(230,"TRIFECTA",'',"noun","a bet in which the bettor selects the first, second and third finishers in a contest or race in the correct order.","medium"),
(231,"SHINGLE",'',"noun","coarse and rounded detritus found on the seashore and which is different from regular gravel due to its large size.","medium"),
(232,"MASON",'',"noun","a skilled artisan who builds using stone, brick or concrete.","medium"),
(233,"AVOID",'',"verb","to stay clear of : to keep away from.","medium"),
(234,"STATIC",'',"adjetive","stable, stagnant.","medium"),
(235,"SAMPLES",'',"plurl noun","portions to represent a whole.","medium"),
(236,"MODERN",'',"adjetive","contemporary : relating to the present time.","medium"),
(237,"CHALK",'',"noun","the prepared form of a soft limestone, earthy in texture and white, gray or buff in color used for marking or drawing.","medium"),
(238,"CONCENTRATE",'',"verb","to bring all one's powers, faculties or activities to bear.","medium"),
(239,"PROUD",'',"adjetive","elated : highly pleased.","medium"),
(240,"EXPIRATION",'',"noun","termination, close, extinction.","medium"),
(241,"BATTERIES",'',"plurl noun","level of enthusiasm or energy.","medium"),
(242,"CENTURIES",'',"plurl noun","time spans of 100 years.","medium"),
(243,"DIFFERED",'',"verb","varied : changed from time to time.","medium"),
(244,"FEARSOME",'',"adjetive","arousing from fright or terror.","medium"),
(245,"FIERCEST",'',"adjetive","characterized by the most furious unrestrained vehemence or zeal.","medium"),
(246,"RESIDENCE",'',"noun","the place where one lives or has their home.","medium"),
(247,"ABATED",'',"verb","lessened : decreased in force.","medium"),
(248,"SCATTERING",'',"verb","spreading widely and randomly by throwing about.","medium"),
(249,"TOPPLED",'',"verb","tumbled down : fell from top-heaviness.","medium"),
(250,"VANE",'',"noun","a movable device used to show the direction of the wind.","medium"),
(251,"VORTICES",'',"plurl noun","tornadoes : quickly moving and spiraling columns of air.","medium"),
(252,"TURBULENT",'',"adjetive","tempestuous or stormy.","medium"),
(253,"OBSTACLES",'',"plurl noun","things that hinder progress or stand in the way.","medium"),
(254,"CONTINENTAL",'',"adjetive","being the portion of the United States located on the continent of North America.","medium"),
(255,"DEPORTMENT",'',"noun","behavior or conduct.","medium"),
(256,"EXHIBITS",'',"plurl noun","exhibitions or displays.","medium"),
(257,"AGRICULTURAL",'',"adjetive","relating to or used in the science or art of working the soil, harvesting crops and raising livestock.","medium"),
(258,"MOMENTOUS",'',"adjetive","weighty : of great importance.","medium"),
(259,"DISTURBANCE",'',"noun","an interruption of quiet or peace.","medium"),
(260,"WILY",'',"adjetive","crafty : full of deceitful cunning.","medium"),
(261,"ROOKIE",'',"noun","a member who is new to an athletic team.","medium"),
(262,"TRANSPARENCIES",'',"plurl noun","matters for displaying which are made on glass, thin cloth, paper or film and which are viewed by the help of light shining through the matter.","medium"),
(263,"HAZMAT",'',"noun","a substance that is shipped and which would be dangerous to life or the environment if released without proper precaution.","medium"),
(264,"ANTARCTIC",'',"adjetive","relating to the South Pole or the region surrounding it.","medium"),
(265,"PERFUME",'',"noun","a fluid containing essences of flowers or synthetics which is used for its scent.","medium"),
(266,"PLAITING",'',"noun","braiding : the interweaving of three or more strands of hair.","medium"),
(267,"WRITERS",'',"plurl noun","people who practice the act of literary or journalistic composition in words as a job.","medium"),
(268,"SERIES",'',"noun","a group of three or more things or events succeeding in order and having a relationship to each other.","medium"),
(269,"AUDIENCE",'',"noun","those present at a stage or film production or viewing of a televised program.","medium"),
(270,"INSUBSTANTIAL",'',"adjetive","imaginary : lacking substance.","medium"),
(271,"STAGGERED",'',"verb","swayed or tottered when standing or walking.","medium"),
(272,"ASSISTANCE",'',"noun","aid given to the needy, usually in monetary form.","medium"),
(273,"SANITIZED",'',"verb","made hygienic through sterilization or cleaning.","medium"),
(274,"DIMINISHED",'',"verb","decreased.","medium"),
(275,"ORGANIST",'',"noun","someone who plays any of several large musical instruments which produce sustained tones by means of a keyboard.","medium"),
(276,"OPERATOR",'',"noun","someone in charge of a telephone switchboard.","medium"),
(277,"LOUISIANA",'',"geogaphical entry","a state in the southern United States. ","medium"),
(278,"PERPETUAL",'',"adjetive","constant or indefinitely.","medium"),
(279,"BLUSTERY",'',"adjetive","stormy.","medium"),
280,"MOLARS",'',"plurl noun","teeth which are adapted for grinding due to having rounded or flattened surfaces.","medium",
281,"ARRANGE",'',"verb","to put in the correct or desired order.","medium",
282,"DISSOLVED",'',"verb","passed into an act by which a solid, liquid or gaseous substance is mixed typically with a liquid.","medium",
283,"EXTREMELY",'',"adveb","in an intense manner.","medium",
284,"PLASTIC",'',"noun","any of a large group of materials of high molecular weight that usually contain a synthetic or semisynthetic organic substance, that are molded into objects of all sizes and shapes.","medium",
285,"MULTIPLICATION",'',"noun","a mathematical operation in which the first number is repeated as many times as there are units in the second number.","medium",
286,"MIDDLE",'',"noun","the part halfway between two points.","medium",
287,"REASONABLE",'',"adjetive","not absurd or ridiculous : being in agreement with right thinking.","medium",
288,"CLOSET",'',"noun","a recess or cabinet used to hold china, clothing or other utensils.","medium",
289,"INVESTIGATION",'',"noun","study or research.","medium",
290,"ACCIDENT",'',"noun","an event that occurs by chance.","medium",
291,"DISCUSSION",'',"noun","a consideration of a question typically occurring in informal debate.","medium",
292,"CONFUSED",'',"verb","confounded : failed to distinguish between two or more parties.","medium",
293,"MICROWAVE",'',"verb","to cook or heat food in an oven that prepares the food with short electromagnetic waves.","medium",
294,"GABLED",'',"adjetive","furnished with the vertical triangular portion of the end of a building.","medium",
295,"SETTLE",'',"verb","seat : to cause to sit.","medium",
296,"SOMBER","SOMBRE","adjective","dejected in appearance or mood : gloomy.","medium",
297,"TAMPERED",'',"verb","interfered with so as to change for the worse.","medium",
298,"LOYAL",'',"adjetive","devoted to a person : faithful.","medium",
299,"REMARKABLE",'',"adjetive","worthy of being noticed.","medium",
300,"JOISTS",'',"plurl noun","the small timbers or iron or steel beams that are arranged in a parallel fashion stretching from wall to wall in a building.","medium",
301,"SCRAMBLING",'',"verb","moving with urgency.","medium",
302,"INSPECTOR",'',"noun","a police officer ranking below a superintendent.","medium",
303,"DISTRESSED",'',"adjetive","overcome with pain or grief.","medium",
304,"SMUDGE",'',"noun","a splotch or smear.","medium",
305,"THROTTLE",'',"verb","to choke : to stop the breathing of by any means.","medium",
306,"PERFECTION",'',"noun","flawlessness : freedom from defect.","medium",
307,"CAPABLE",'',"adjetive","marked by general efficiency and by adequate resourcefulness, skill and reliability.","medium",
308,"GADGETS",'',"plurl noun","typically small devices that are often considered novelties and that are found especially on pieces of machinery.","medium",
309,"CHANNEL",'',"noun","a band of frequencies able to accommodate a single television or radio communication.","medium",
310,"CHISEL",'',"noun","a tool consisting of a metal bar with a sharpened edge at one end used for working on the surface of materials by chipping or carving.","medium",
311,"CHIMNEY",'',"noun","a vertical structure incorporated into a building that carries off smoke, fumes or gases.","medium",
312,"MINNOW",'',"noun","a very small fish that can grow up to three inches long and that is common in streams.","medium",
313,"DOMAIN",'',"noun","a large subdivision of the Internet denoted by an abbreviation consisting of computers or sites with a common purpose or a common location.","medium",
314,"SHUFFLE",'',"verb","to slide the feet back and forth without lifting them.","medium",
315,"CARPENTER",'',"noun","a person whose career is to build or repair with wood.","medium",
316,"PRUNERS",'',"plurl noun","a tool which is used to remove dead branches or leaves from vegetation.","medium",
317,"PARCEL",'',"noun","a package.","medium",
318,"SQUAWK",'',"verb","to emit a loud harsh cry.","medium",
319,"SHEETROCK",'',"tradmark","— used to describe a plasterboard formed of gypsum between two surfaces of hard paper.","medium",
320,"TROWEL",'',"noun","a hand tool with a blade that is used to apply, spread, shape and smooth any loose material.","medium",
321,"NERVOUS",'',"adjetive","originating in or affected by the nerves.","medium",
322,"SPIRIT",'',"noun","any supernatural being such as an apparition or elf.","medium",
323,"EQUATOR",'',"noun","the circle of the celestial sphere whose plane runs perpendicular to the axis of Earth.","medium",
324,"EVIDENCE",'',"noun","something submitted legally to a tribunal as a means of realizing the truth of any alleged matter of fact under investigation before it.","medium",
325,"SOLAR",'',"adjetive","related to the sun and its effects on Earth and other planets.","medium",
326,"EXPLORE",'',"verb","to search or look into.","medium",
327,"DISTANCE",'',"noun","the amount of separation between two points.","medium",
328,"FAULT",'',"noun","responsibility for failure.","medium",
329,"COLONISTS",'',"plurl noun","someone who settles in a new country.","medium",
330,"PRUDENCE",'',"noun","wisdom shown in the exercise of self-control and reason.","medium",
331,"ASSEMBLY",'',"noun","a meeting scheduled for an entire student body and faculty of a school held for recreational, administrative or educational reasons.","medium",
332,"SHERIFF",'',"noun","an important county officer in the United States who is typically elected by the people.","medium",
333,"TARRY",'',"verb","to dawdle or procrastinate.","medium",
334,"ENTITY",'',"noun","something that has an objective or physical reality and distinct character.","medium",
335,"ARCHIVES",'',"plurl noun","repositories for documents of historical value.","medium",
336,"COMMOTION",'',"noun","noisy confusion.","medium",
337,"VACANCY",'',"noun","an empty office or post.","medium",
338,"BEATBOXING",'',"noun","a musical style comprised of solo vocal imitation of percussion.","medium",
339,"MUTATE",'',"verb","to undergo a significant alteration.","medium",
340,"COMMONPLACE",'',"noun","a comment or remark lacking in originality.","medium",
341,"GINGERBREAD",'',"noun","a cake made with molasses and ginger which is then cut in fancy shapes and frosted.","medium",
342,"DISPUTE",'',"verb","to wrangle : to argue with persistence.","medium",
343,"EPISODE",'',"noun","a part of a television or radio serial presented in one period.","medium",
344,"CONFECTION",'',"noun","a delicacy.","medium",
345,"AUTOGRAPHS",'',"plurl noun","handwritten signatures.","medium",
346,"PETITE",'',"adjetive","little or small.","medium",
347,"STATION",'',"noun","a post or position of duty.","medium",
348,"WITHERS",'',"plurl noun","the ridge on a horse that falls between the shoulder bones.","medium",
349,"HUNKY-DORY",'',"adjetive","fine.","medium",
350,"IGNOBLE",'',"adjetive","despicable.","hard",
351,"DIAPHORESIS",'',"noun","profuse sweating.","hard",
352,"KURTA",'',"noun","a long, loosely fitting shirt without a collar that originated in India.","hard",
353,"HYPERION",'',"noun","a Titan who fathered Helios, Selene and Eos.","hard",
354,"LACROSSE",'',"noun","a game played with two teams of 10 players each with each player using a long-handled stick to catch and throw a ball, and with the object being to throw the ball into the opponents' goal.","hard",
355,"GEIGER",'',"noun","a tool which consists of a gas-filled counting tube whose purpose is to detect the presence of cosmic rays or radioactive substances.","hard",
356,"THERMOHALINE",'',"adjetive","in oceanography, involving the joined effect of salinity and temperature.","hard",
357,"GANNET",'',"noun","any of several large web-footed sea birds.","hard",
358,"PALLADIUM",'',"noun","something that provides protection.","hard",
359,"BREVET",'',"noun","a document which grants a privilege or title on behalf of the government.","hard",
360,"PAMPHLET",'',"noun","an unbound publication with a small number of pages.","hard",
361,"PALINDROME",'',"noun","a word or sentence that reads the same both forwards and backwards.","hard",
362,"VISITE",'',"noun","a short coat that was formerly worn in the summertime by women.","hard",
363,"SATSUMA",'',"noun","a cultivated mandarin tree producing seedless fruit.","hard",
364,"STIRRUPS",'',"plurl noun","rings or bent pieces of metal, wood or leather made to hold and support the foot of a rider on horseback.","hard",
365,"CONNEMARA",'',"geogaphical entry","a district in Ireland located in western Galway.","hard",
366,"ABUNDANCE",'',"noun","a large supply.","hard",
367,"CALAMITOUS",'',"adjetive","marked by disaster.","hard",
368,"DROPSONDE",'',"noun","a miniature radio transmitter which is dropped by a parachute in order to measure the temperature and moisture of the air.","hard",
369,"PROCLAMATION",'',"noun","an official formal public announcement.","hard",
370,"HOKUM",'',"noun","a device used to elicit a desired reaction from an audience.","hard",
371,"COLOSSAL",'',"adjetive","characterized by extreme bulk, force, power or strength.","hard",
372,"COLTAN",'',"noun","a dull black ore that is a mixture of columbite and tantalite.","hard",
373,"SQUADRON",'',"noun","a division of organization in the military.","hard",
374,"MARINATE",'',"verb","to set meat, fish or vegetables in a liquid infused with vinegar or oil, spices and herbs.","hard",
375,"ANAGRAMS",'',"plurl noun","phrases or words that are created from the letters of other words or phrases.","hard",
376,"VERANDAS","VERANDAHS","plural noun","porches.","hard",
377,"HIMALAYAN",'',"noun","a breed of domestic cats.","hard",
378,"MCINTOSH",'',"noun","a bright red apple for eating.","hard",
379,"ASPERSIONS",'',"plurl noun","slanderous expressions.","hard",
380,"CULMINATE",'',"verb","to reach a decisive point.","hard",
381,"HELIUM",'',"noun","a very light colorless inert gas used for diluting oxygen, inflating balloons, and in many chemical and metallurgical processes.","hard",
382,"STEEPLECHASING",'',"noun","the sport of horse riding in races which involve jumping over barriers.","hard",
383,"TEFLON",'',"tradmark","— used for a tough resin characterized by good resistance to chemicals, heat and weathering.","hard",
384,"BANTAM",'',"adjetive","small.","hard",
385,"APPRENTICE",'',"noun","a person who is in training to learn a trade from a skilled worker.","hard",
386,"RELUCTANT",'',"adjetive","unwilling.","hard",
387,"HERITAGE",'',"noun","a legacy.","hard",
388,"SOJOURNER",'',"noun","a person who stays somewhere as a temporary resident.","hard",
389,"DEROGATORY",'',"adjetive","expressive of disdain.","hard",
390,"PALSY",'',"noun","partial or complete loss of motion or sensation in any part of the body.","hard",
391,"LASCAUX",'',"geogaphical entry","a cave in France that contains prehistoric paintings.","hard",
392,"SYNESTHESIA","SYNAESTHESIA","noun","a subjective image or sensation of a sense such as a color different from the one such as a sound that is being stimulated.","hard",
393,"NEFARIOUS",'',"adjetive","detestable or wicked.","hard",
394,"HALOGENS",'',"plurl noun","the five elements fluorine, chlorine, bromine, iodine and astatine that form group VII A of the periodic table.","hard",
395,"GALLIUM",'',"noun","a rare bluish-white metallic element that is hard and brittle at low temperatures, melts just above room temperature and expands on freezing.","hard",
396,"SMELTERS",'',"plurl noun","furnace operators who fuse or melt ore often with an accompanying chemical change typically to separate the metal.","hard",
397,"HYMNAL",'',"noun","a collection of church songs that have been adapted for singing during religious services.","hard",
398,"TARTARIC",'',"adjetive","relating to or derived from a substance containing a white crystalline salt and yeast or a type of acid obtained from that substance.","hard",
399,"BINDI",'',"noun","a piece of jewelry or a mark such as a red spot worn on the forehead especially by Hindu women.","hard",
400,"HAITIAN",'',"adjetive","relating to the people of Haiti or the island itself.","hard",
401,"DIVAN",'',"noun","a type of couch that usually doesn't have arms or a back and is often meant to be used as a bed.","hard",
402,"BADMINTON",'',"noun","a game played on a court by two or four people who use rackets to volley a shuttlecock over a net.","hard",
403,"BAYONET",'',"noun","a steel blade made to be attached to the muzzle end of a type of firearm that is fired while braced against the shoulder.","hard",
404,"CURRYCOMB",'',"noun","a grooming tool for horses that has rows of serrated ridges or metallic teeth.","hard",
405,"HAUGHTY",'',"adjetive","arrogant or disdainfully proud.","hard",
406,"HESITATE",'',"verb","to delay or pause typically for a moment.","hard",
407,"OPPORTUNITY",'',"noun","a combination of time, place and circumstances that is favorable or suitable for a specific action or activity.","hard",
408,"APOLLO",'',"noun","a young man of graceful beauty.","hard",
409,"ACCORDANCE",'',"noun","agreement, such as of opinion, action or will.","hard",
410,"ATMOSPHERIC",'',"adjetive","relating to the entire mass of air that surrounds Earth.","hard",
411,"LEVEES",'',"plurl noun","raised earth or gravel structures that are designed to prevent flooding.","hard",
412,"PRECARIOUSLY",'',"adveb","in a manner marked by a lack of stability or security.","hard",
413,"PROPORTIONATE",'',"adjetive","being in balance or symmetry.","hard",
414,"SUFFUSED",'',"verb","flushed, filled.","hard",
415,"ACCELERATES",'',"verb","speeds up the normal development or progress of something.","hard",
416,"COINCIDENCE",'',"noun","the conjunction of circumstances or events significant to one another but that have no obvious causal connection.","hard",
417,"PRESTIGIOUS",'',"adjetive","having a greatly respected name or reputation : esteemed : honored.","hard",
418,"EMPHATIC",'',"adjetive","commanding attention by insistence or prominence.","hard",
419,"CONTAMINATED",'',"verb","deemed not fit for use by the introduction of elements that are undesirable or unwholesome.","hard",
420,"MADAGASCAR",'',"geogaphical entry","an island in the western Indian Ocean off southeastern Africa that is known for its unique flora and fauna.","hard",
421,"EXPOSURE",'',"noun","a condition of being subjected to an influence or to an experience.","hard",
422,"PARACHUTED",'',"verb","descended by means of a folding umbrella-shaped device made of light fabric that is used to slow the speed of the person or thing attached to it.","hard",
423,"PERIODICALLY",'',"adveb","frequently : recurrently.","hard",
424,"INTRIGUING",'',"adjetive","fascinating.","hard",
425,"ABSORPTIVE",'',"adjetive","characterized by, tending to or causing assimilation.","hard",
426,"INCOMPREHENSIBLE",'',"adjetive","existing beyond the reach of the human mind.","hard",
427,"MERRIMACK",'',"geogaphical entry","a river in southern New Hampshire and northeastern Massachusetts that flows south and northeast into the Atlantic.","hard",
428,"SINAI",'',"geogaphical entry","a peninsula in northeastern Egypt between the Red Sea and the Mediterranean that forms an extension of the continent of Asia.","hard",
429,"MISDEMEANOR","MISDEMEANOUR","noun","a crime that is not punishable by death or imprisonment in a state penitentiary.","hard",
430,"ASPARAGUS",'',"noun","a plant that is widely grown for its edible and tender young shoots.","hard",
431,"SOLACE",'',"verb","to console.","hard",
432,"ARGYRIA",'',"noun","permanent dark skin discoloration caused by absorption after overuse of medicinal silver preparations.","hard",
433,"GUANINE",'',"noun","a crystalline purine base found especially in the excrement of bats and in many leguminous plants and that is obtained by hydrolysis of nucleic acids.","hard",
434,"XYLYL",'',"noun","any of several isomeric radicals each with a valence of one that is derived from the three xylenes by the removal of a hydrogen atom.","hard",
435,"THERAPEUTIC",'',"adjetive","relating to the treatment of disease or disorders by medicinal or curing agents or methods: curative.","hard",
436,"TUMULTUOUS",'',"adjetive","marked by overwhelming or violent commotion, turbulence or radical change.","hard",
437,"COMMODORE",'',"noun","an officer of the navy who typically ranks next below a rear admiral and above a captain.","hard",
438,"PLAYWRIGHT",'',"noun","a person who writes a composition arranged for enactment by actors, intended to tell a story through the actions and usually dialogue of the actors.","hard",
439,"SENILE",'',"adjetive","displaying a loss of mental abilities associated with old age.","hard",
440,"LARYNGITIS",'',"noun","inflammation of the vocal cords.","hard",
441,"PROXIMO",'',"adjetive","of or taking place in the next month after the current one.","hard",
442,"GUERRILLA","GUERILLA","noun","a member of an independent band engaged in plundering, violent wartime military expeditions.","hard",
443,"GIZA",'',"geogaphical entry","a city in northern Egypt that is near Cairo and that lies on the western bank of the Nile River.","hard",
444,"FIXITY",'',"noun","the state or quality of being stable or not subject to change or fluctuation.","hard",
445,"JODHPURS",'',"plurl noun","pants for horseback riding that are full through the hips, fit closely from the knee to the ankle and typically have a strap under each foot.","hard",
446,"HYDRARGYRUM",'',"noun","the element mercury.","hard",
447,"CARBORANE",'',"noun","any of a class of compounds that are thermally stable and that are used in the synthesis of lubricants and polymers.","hard",
448,"DENOUNCEMENT",'',"noun","the act of making known or declaring someone such as a culprit to people in command.","hard",
449,"COLUMBIA",'',"noun","the United States.","hard");
  

-- insert into userSpellingBee
--     wordId, definitionId, userId, correct, incorrect)
-- VALUES
--     1, 1, 1, 'yes', 'no');

insert into users
    (name,emailUsername, hash)
values
    ('Casey', 'fayardcasey@gmail.com',  'terminus1');

